<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.AKBtWjC' shared service.

return $this->privates['.service_locator.AKBtWjC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AuthentificationController::register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\CompteController::delete' => ['privates', '.service_locator.M30T2zO', 'get_ServiceLocator_M30T2zOService.php', true],
    'App\\Controller\\CompteController::edit' => ['privates', '.service_locator.M30T2zO', 'get_ServiceLocator_M30T2zOService.php', true],
    'App\\Controller\\CompteController::index' => ['privates', '.service_locator.JfrEn5y', 'get_ServiceLocator_JfrEn5yService.php', true],
    'App\\Controller\\CompteController::new' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\CompteController::show' => ['privates', '.service_locator.M30T2zO', 'get_ServiceLocator_M30T2zOService.php', true],
    'App\\Controller\\PartenaireController::Add' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\AuthentificationController:register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\CompteController:delete' => ['privates', '.service_locator.M30T2zO', 'get_ServiceLocator_M30T2zOService.php', true],
    'App\\Controller\\CompteController:edit' => ['privates', '.service_locator.M30T2zO', 'get_ServiceLocator_M30T2zOService.php', true],
    'App\\Controller\\CompteController:index' => ['privates', '.service_locator.JfrEn5y', 'get_ServiceLocator_JfrEn5yService.php', true],
    'App\\Controller\\CompteController:new' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\CompteController:show' => ['privates', '.service_locator.M30T2zO', 'get_ServiceLocator_M30T2zOService.php', true],
    'App\\Controller\\PartenaireController:Add' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
], [
    'App\\Controller\\AuthentificationController::register' => '?',
    'App\\Controller\\CompteController::delete' => '?',
    'App\\Controller\\CompteController::edit' => '?',
    'App\\Controller\\CompteController::index' => '?',
    'App\\Controller\\CompteController::new' => '?',
    'App\\Controller\\CompteController::show' => '?',
    'App\\Controller\\PartenaireController::Add' => '?',
    'App\\Controller\\AuthentificationController:register' => '?',
    'App\\Controller\\CompteController:delete' => '?',
    'App\\Controller\\CompteController:edit' => '?',
    'App\\Controller\\CompteController:index' => '?',
    'App\\Controller\\CompteController:new' => '?',
    'App\\Controller\\CompteController:show' => '?',
    'App\\Controller\\PartenaireController:Add' => '?',
]);
