<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJSd3x68\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJSd3x68/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerJSd3x68.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerJSd3x68\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerJSd3x68\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'JSd3x68',
    'container.build_id' => '797768a9',
    'container.build_time' => 1564492178,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJSd3x68');
