<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXpTeiYR\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXpTeiYR/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXpTeiYR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerXpTeiYR\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerXpTeiYR\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'XpTeiYR',
    'container.build_id' => '25679db2',
    'container.build_time' => 1564534870,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXpTeiYR');
