<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5NHbDIX\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5NHbDIX/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container5NHbDIX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container5NHbDIX\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \Container5NHbDIX\srcApp_KernelTestDebugContainer([
    'container.build_hash' => '5NHbDIX',
    'container.build_id' => '2b2ea84d',
    'container.build_time' => 1564405309,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5NHbDIX');
