<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYcqxzVo\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYcqxzVo/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYcqxzVo.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYcqxzVo\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYcqxzVo\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YcqxzVo',
    'container.build_id' => '4999f9c4',
    'container.build_time' => 1564252103,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYcqxzVo');
