<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKWxMPd1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKWxMPd1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKWxMPd1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKWxMPd1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKWxMPd1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KWxMPd1',
    'container.build_id' => 'b6457cbe',
    'container.build_time' => 1564326444,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKWxMPd1');
